asset:
  login-background-url: /branding/cloudbase/cloudbase-login-background.svg

idp:
  identifierdefaultbannerlogo: branding/cloudbase/cloudbase-logo.svg
  default_sign_in_page_text: Cloudbase
  default_logo_target_uri: https://cloud.opencloud.test

clients:
  - id: web
    name: Cloudbase web app
    application_type: web
    insecure: true
    trusted: true
    redirect_uris:
      - https://host.docker.internal:9200/
      - https://host.docker.internal:9200/oidc-callback.html
      - https://host.docker.internal:9200/oidc-silent-redirect.html
      - https://host.docker.internal:9201/
      - https://host.docker.internal:9201/oidc-callback.html
      - https://host.docker.internal:9201/oidc-silent-redirect.html
      - https://oc.opencloud.test:10200/
      - https://oc.opencloud.test:10200/oidc-callback.html
      - https://oc.opencloud.test:10200/oidc-silent-redirect.html
      - https://oc.opencloud.test:10201/
      - https://oc.opencloud.test:10201/oidc-callback.html
      - https://oc.opencloud.test:10201/oidc-silent-redirect.html
    origins:
      - https://host.docker.internal:9200
      - https://host.docker.internal:9201
      - https://oc.opencloud.test:10200
      - https://oc.opencloud.test:10201

  - id: OpenCloudDesktop
    name: Cloudbase desktop client
    application_type: 'native'
    trusted: true
    redirect_uris:
      - http://localhost
      - http://127.0.0.1
